### ISSUE TITLE
How can I build it from source?

### ISSUE THREAD

**Issue by hannhu** [cisco/mindmeld#272]
Hello guys, I'm interested in mindmeld and want to be one of contributors, so how can I build it from source? I have only found how to install it via pip.

**Comment by vijay120** [comment]
Hi, you can follow the instructions here (https://www.mindmeld.com/docs/userguide/getting_started.html#id1) to getting started. Since the project is written in python, there is not compilation step. One has to install and run a few dependencies before running MindMeld and sample applications built on top of it.
