### ISSUE TITLE
persian language support

### ISSUE THREAD

**Issue by mohammad69h94** [cisco/mindmeld#327]
Does MindMeld support the Persian language? 
It can not make entity "store_name" and show the following error:
  Unknown entity ' store_name' found in query 'فروشگاه میدان مرکزی  چه زمانی بسته می شود؟'

The text in the file "train.txt" in "get_store_hourse" attached to this issue
[train.txt](https://github.com/cisco/mindmeld/files/6724192/train.txt)
I tested different types of formats in this file, but it still can't read and train this file. for example, I remove "{}, |, store_name" and so on.

In fact, inline annotations for the Persian language do not support it, what should I do? how to change the config to pass it?

**Comment by mohammad69h94** [comment]
>>>mm.configure_logs()
>>> blueprint = 'myapp'
>>> mm.blueprint(blueprint)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mohammadali/miniconda3/envs/pythonProject2/lib/python3.6/site-packages/mindmeld/_util.py", line 97, in __call__
    raise ValueError("Unknown blueprint name: {!r}".format(name))
ValueError: Unknown blueprint name: 'myapp'
>>> 
>>> from mindmeld.components import NaturalLanguageProcessor
>>> nlp = NaturalLanguageProcessor(blueprint)
Language code "fa" is not supported for stemming. If stemming is enabled in config.py, consider disabling it.
>>> nlp.build()
Fitting intent classifier: domain='store_info'
Loading raw queries from file myapp/domains/store_info/exit/train.txt
Loading raw queries from file myapp/domains/store_info/find_nearest_store/train.txt
Loading raw queries from file myapp/domains/store_info/get_store_hours/train.txt
Loading raw queries from file myapp/domains/store_info/greet/train.txt
Loading raw queries from file myapp/domains/store_info/help/train.txt
Loading queries from file myapp/domains/store_info/exit/train.txt
Loading queries from file myapp/domains/store_info/find_nearest_store/train.txt
Loading queries from file myapp/domains/store_info/get_store_hours/train.txt
Unknown entity ' store_name' found in query 'فروشگاه میدان مرکزی  چه زمانی بسته می شود؟'
Loading queries from file myapp/domains/store_info/greet/train.txt
Loading queries from file myapp/domains/store_info/help/train.txt
Selecting hyperparameters using k-fold cross-validation with 10 splits
Best accuracy: 94.97%, params: {'C': 100, 'class_weight': {0: 1.0, 1: 1.0, 2: 1.0, 3: 1.0, 4: 1.0}, 'fit_intercept': False}
Fitting entity recognizer: domain='store_info', intent='get_store_hours'
Loading raw queries from file myapp/domains/store_info/get_store_hours/testtrain123.txt
Loading queries from file myapp/domains/store_info/get_store_hours/testtrain123.txt
There are no labels in this label set, so we don't fit the model.
Fitting entity recognizer: domain='store_info', intent='find_nearest_store'
There are no labels in this label set, so we don't fit the model.
Fitting entity recognizer: domain='store_info', intent='help'
There are no labels in this label set, so we don't fit the model.
Fitting entity recognizer: domain='store_info', intent='greet'
There are no labels in this label set, so we don't fit the model.
Fitting entity recognizer: domain='store_info', intent='exit'
There are no labels in this label set, so we don't fit the model.
>>>

**Comment by serapio** [comment]
Hi @mohammad69h94 , we haven't tested MindMeld with Persian language, but here are possible solutions to the issues you are seeing:
1. The error about store_name would normally mean that it did not find a entity map for it in the entities directory. Is it defined there?
2. Because Farsi does have inflections but does not have a stemmer available, you will probably need to supply more training data or use character ngram features to get robust accuracies. But for a basic proof that the pipeline works, I would leave that issue aside.
3. The version of Duckling that comes with MindMeld does not include support for Persian, which means you would need to only use custom entities. However, the upstream version (https://github.com/facebook/duckling) does include Persian, so it would be fairly straightforward to run that version in place of the default, which would enable system entities based on that. We plan to integrate those Duckling changes soon.
4. The right-to-left script with in-line latin-script annotations is a more subtle problem. There may be a better solution, but you can use a preprocessor to transliterate the input into a romanization of Persian script, and then use the romanized representation internally.

**Comment by mohammad69h94** [comment]
thankyou so much for your help
