### ISSUE TITLE
Expose language parameter

### ISSUE THREAD

**Issue by derekmpham** [cisco/mindmeld#83]
Not exposing non-English languages--implementing Vietnamese version of Kwik-E-Mart app. Need to expose language parameter in Application and ApplicationManager classes, as well as pass language parameter into nlp.process(). See PR #82

**Comment by minhtuev** [comment]
Nice! This is a change that we really need and overlooked in the previous implementation!

**Comment by minhtuev** [comment]
We have changed the interface due so that we can add language and locale param for each NLP object directly. In the future, we might revisit setting a default language for an application when we add native support for multiple languages. We will descope this PR to simply add the Vietnamese version of Kwik E Mart.

https://github.com/cisco/mindmeld/pull/98
