### ISSUE TITLE
Remove es_host from Application Manager

### ISSUE THREAD

**Issue by minhtuev** [cisco/mindmeld#91]
`es_host` is not used and we should refactor the interface to remove redundancy and confusion.

**Comment by MisterOrange00** [comment]
how should one specify the host for ES if it is not living on the same machine (let's say a remote cluster) if not through this interface ?

**Comment by rfinz** [comment]
+1 just emailed to ask the same question!

**Comment by MisterOrange00** [comment]
So I plunged into the code and saw that while building (Docker) or running Mindmeld you could specify an OS environment variable $MM_ES_HOST from which it will connect. I tried it and it worked for me. Some of the code using this environment variable seemed to be legacy but the line 150 of _util.py looks solid. Can someone confirm this is the way to do nowand if it is going to stay that way ? 

I ran into this problem because in my setup (a docker-compose with duckling and elastic-search in already running containers) the address changed between build time (0.0.0.0) and run time (docker's DNS http://duckling and http://elastic-search). So I modified the config.py file so it read from a $MM_DUCK_HOST variable similarly to elastic.

Hope it helps you @rfinz. Thank you the team for this awesome project !
